melons = {'alib': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Ali-Baba-Watermelon-web.jpg',
  'name': 'Ali Baba Watermelon',
  'price': 2.5,
  'seedless': 1},
 'anci': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Ancient-Watermelon-web.jpg',
  'name': 'Ancient Watermelon',
  'price': 3.0,
  'seedless': 0},
 'arkb': {'category': 'Watermelon',
  'color': 'black',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Arkansas-Black-Watermelon-web.jpg',
  'name': 'Arkansas Black Watermelon',
  'price': 4.0,
  'seedless': 1},
 'chrc': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/watermelon-criss-cross.jpg',
  'name': 'Chris Cross Watermelon',
  'price': 2.5,
  'seedless': 0},
 'cong': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/watermelon-congo.jpg',
  'name': 'Congo Watermelon',
  'price': 2.0,
  'seedless': 1},
 'cren': {'category': 'Hybrid',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimRegular/crenshaw.jpg',
  'name': 'Crenshaw',
  'price': 2.0,
  'seedless': 1},
 'cris': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Crimson-Sweet-Watermelon-web.jpg',
  'name': 'Crimson Sweet Watermelon',
  'price': 1.75,
  'seedless': 0},
 'desk': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Desert-King-Watermelon-web.jpg',
  'name': 'Desert King Watermelon',
  'price': 2.0,
  'seedless': 1},
 'dixq': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Dixie-Queen-Watermelon-web.jpg',
  'name': 'Dixie Queen Watermelon',
  'price': 2.0,
  'seedless': 0},
 'fair': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Fairfax-Watermelon-web-2.jpg',
  'name': 'Fairfax Watermelon',
  'price': 2.0,
  'seedless': 0},
 'golh': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Golden-Honey-Watermelon-web.jpg',
  'name': 'Golden Honey Watermelon',
  'price': 2.5,
  'seedless': 1},
 'golm': {'category': 'Watermelon',
  'color': 'gold',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Golden-Midget-Watermelon-web.jpg',
  'name': 'Golden Midget Watermelon',
  'price': 2.5,
  'seedless': 0},
 'hopy': {'category': 'Watermelon',
  'color': 'gold',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Hopi-Yellow-Watermelon-web.jpg',
  'name': 'Hopi Yellow Watermelon',
  'price': 2.5,
  'seedless': 1},
 'irig': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/watermelon-irish-grey.jpg',
  'name': 'Irish Grey Watermelon',
  'price': 2.5,
  'seedless': 0},
 'jubb': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Jubilee-Bush-Watermelon-web.jpg',
  'name': 'Jubilee Bush Watermelon',
  'price': 2.5,
  'seedless': 1},
 'jubi': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Jubilee-Watermelon-web.jpg',
  'name': 'Jubilee Watermelon',
  'price': 2.5,
  'seedless': 0},
 'ledm': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Ledmon-Watermelon-web.jpg',
  'name': 'Ledmon Watermelon',
  'price': 3.0,
  'seedless': 1},
 'mala': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Malali-Watermelon-web.jpg',
  'name': 'Malali Watermelon',
  'price': 2.0,
  'seedless': 0},
 'meli': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Melitopolski-Watermelon-web.jpg',
  'name': 'Melitopolski Watermelon',
  'price': 3.0,
  'seedless': 1},
 'monm': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/watermelon-montenegro-man.jpg',
  'name': 'Montenegro Man Melon',
  'price': 2.5,
  'seedless': 0},
 'moon': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimRegular/Watermelon-Early-Moonbeam-WM197-web1.jpg',
  'name': 'Moonbeam Watermelon',
  'price': 2.25,
  'seedless': 1},
 'moos': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Moon-and-Stars-Watermelon-web.jpg',
  'name': 'Moon and Stars Watermelon',
  'price': 2.5,
  'seedless': 0},
 'navw': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Navajo-Winter-Watermelon-web.jpg',
  'name': 'Navajo Winter Watermelon',
  'price': 3.0,
  'seedless': 1},
 'oran': {'category': 'Watermelon',
  'color': 'white',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Orange-Glo-watermelon-web.jpg',
  'name': 'Orangeglo Watermelon',
  'price': 2.75,
  'seedless': 0},
 'royg': {'category': 'Watermelon',
  'color': 'gold',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Royal-Golden-Watermelon-web.jpg',
  'name': 'Royal Golden Watermelon',
  'price': 2.25,
  'seedless': 1},
 'scab': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Scaly-Bark-Watermelon-web-.jpg',
  'name': 'Scaly Bark Watermelon',
  'price': 4.0,
  'seedless': 1},
 'stom': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Stone-Mountain-Watermelon-web.jpg',
  'name': 'Stone Mountain Watermelon',
  'price': 3.0,
  'seedless': 0},
 'sugb': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Sugar-Baby-Watermelon-web.jpg',
  'name': 'Sugar Baby Watermelon',
  'price': 2.5,
  'seedless': 1},
 'takg': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Takii-Gem-Watermelon-web.jpg',
  'name': 'Takii Gem Watermelon',
  'price': 2.75,
  'seedless': 0},
 'tend': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/watermelon-tendergold.jpg',
  'name': 'Tendergold Watermelon',
  'price': 2.5,
  'seedless': 1},
 'texg': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Texas-Golden-2-Watermelon-web.jpg',
  'name': 'Texas Golden Watermelon',
  'price': 2.75,
  'seedless': 0},
 'thrd': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Thai-Rom-Dao-Watermelon-web.jpg',
  'name': 'Thai Rom Dao Watermelon',
  'price': 2.5,
  'seedless': 1},
 'tomw': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Tom-Watson-Watermelon-web.jpg',
  'name': 'Tom Watson Watermelon',
  'price': 2.25,
  'seedless': 0},
 'whiw': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/White-Wonder-Watermelon-web.jpg',
  'name': 'White Wonder Watermelon',
  'price': 2.5,
  'seedless': 1},
 'wils': {'category': 'Watermelon',
  'color': 'green',
  'img_url': 'http://www.rareseeds.com/assets/1/14/DimThumbnail/Wilsons-Sweet-Watermelon-web.jpg',
  'name': "Wilson's Sweet Watermelon",
  'price': 2.5,
  'seedless': 0}}

states = [
('ALABAMA', 'AL'),
('ALASKA', 'AK'),
('ARIZONA', 'AZ'),
('ARKANSAS', 'AR'),
('CALIFORNIA', 'CA'),
('COLORADO', 'CO'),
('CONNECTICUT', 'CT'),
('DELAWARE', 'DE'),
('FLORIDA', 'FL'),
('GEORGIA', 'GA'),
('HAWAII', 'HI'),
('IDAHO', 'ID'),
('ILLINOIS', 'IL'),
('INDIANA', 'IN'),
('IOWA', 'IA'),
('KANSAS', 'KS'),
('KENTUCKY', 'KY'),
('LOUISIANA', 'LA'),
('MAINE', 'ME'),
('MARYLAND', 'MD'),
('MASSACHUSETTS', 'MA'),
('MICHIGAN', 'MI'),
('MINNESOTA', 'MN'),
('MISSISSIPPI', 'MS'),
('MISSOURI', 'MO'),
('MONTANA', 'MT'),
('NEBRASKA', 'NE'),
('NEVADA', 'NV'),
('NEW HAMPSHIRE', 'NH'),
('NEW JERSEY', 'NJ'),
('NEW MEXICO', 'NM'),
('NEW YORK', 'NY'),
('NORTH CAROLINA', 'NC'),
('NORTH DAKOTA', 'ND'),
('OHIO', 'OH'),
('OKLAHOMA', 'OK'),
('OREGON', 'OR'),
('PENNSYLVANIA', 'PA'),
('RHODE ISLAND', 'RI'),
('SOUTH CAROLINA', 'SC'),
('SOUTH DAKOTA', 'SD'),
('TENNESSEE', 'TN'),
('TEXAS', 'TX'),
('UTAH', 'UT'),
('VERMONT', 'VT'),
('VIRGINIA', 'VA'),
('WASHINGTON', 'WA'),
('WEST VIRGINIA', 'WV'),
('WISCONSIN', 'WI'),
('WYOMING', 'WY')]